-----------------------------------------------------------------------------------------------------------------------------------------
-- LOCALPLAYERS
-----------------------------------------------------------------------------------------------------------------------------------------
LocalPlayer["state"]:set("Route",0,false)
LocalPlayer["state"]:set("Name","",false)
LocalPlayer["state"]:set("Passport",0,false)
LocalPlayer["state"]:set("Rope",false,false)
LocalPlayer["state"]:set("Cancel",false,true)
LocalPlayer["state"]:set("Active",false,false)
LocalPlayer["state"]:set("Handcuff",false,true)
LocalPlayer["state"]:set("Commands",false,true)
LocalPlayer["state"]:set("Spectate",false,false)
LocalPlayer["state"]:set("Invisible",false,false)
LocalPlayer["state"]:set("Invincible",false,false)
LocalPlayer["state"]:set("usingPhone",false,false)
LocalPlayer["state"]:set("Player",GetPlayerServerId(PlayerId()),false)

LocalPlayer["state"]:set("Admin",false,false)
LocalPlayer["state"]:set("PoliciaMilitar",false,false)
LocalPlayer["state"]:set("Core",false,false)
LocalPlayer["state"]:set("PRF",false,false)
LocalPlayer["state"]:set("PCivil",false,false)
LocalPlayer["state"]:set("Paramedic",false,false)
LocalPlayer["state"]:set("Mecanico",false,false)
LocalPlayer["state"]:set("PizzaThis",false,false)
LocalPlayer["state"]:set("Uwucoffee",false,false)
LocalPlayer["state"]:set("BeanMachine",false,false)
LocalPlayer["state"]:set("Ballas",false,false)
LocalPlayer["state"]:set("Vagos",false,false)
LocalPlayer["state"]:set("Families",false,false)
LocalPlayer["state"]:set("Aztecas",false,false)
LocalPlayer["state"]:set("Altruists",false,false)
LocalPlayer["state"]:set("Triads",false,false)
LocalPlayer["state"]:set("Razors",false,false)

LocalPlayer["state"]:set("Buttons",false,true)
LocalPlayer["state"]:set("Cassino",false,false)
LocalPlayer["state"]:set("Race",false,false)
LocalPlayer["state"]:set("Target",false,false)
-----------------------------------------------------------------------------------------------------------------------------------------
-- VRP:ACTIVE
-----------------------------------------------------------------------------------------------------------------------------------------
RegisterNetEvent("vRP:Active")
AddEventHandler("vRP:Active",function(Passport,Name)
    SetDiscordAppId(1378503329608499231)
    SetDiscordRichPresenceAsset("Cinelândia")
    SetRichPresence("#"..Passport.." "..Name)
    SetDiscordRichPresenceAssetSmall("log_512x512")
    SetDiscordRichPresenceAssetText("Cinelândia")
    SetDiscordRichPresenceAssetSmallText("Sua diversão começa aqui com absoluta seriedade.")
    SetDiscordRichPresenceAction(0,"Acesse noso Discord","https://discord.gg/XBwJtrUhaF")
    -- SetDiscordRichPresenceAction(1,"Entrar no servidor","fivem://connect/cfx.re/join/j7j5ya")
    --SetDiscordRichPresenceAction(1,"Siga-nos no Instagram","https://instagram.com/Absolutrp")
    --SetDiscordRichPresenceAction(1,"Mais sobre nós","https://linktr.ee/absolutrp")

end)