-----------------------------------------------------------------------------------------------------------------------------------------
-- MAP SYSTEM (Placeholder)
-----------------------------------------------------------------------------------------------------------------------------------------
-- Este arquivo está reservado para futuras funcionalidades de mapa
-- Por enquanto, mantém-se vazio para evitar erros de carregamento
