var CP = {
  codigopenal: [
    {
      id: 1,
      artigo: "12",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Arma Classe 1",
      descricao: "Porte ou posse ilegal de armamento de baixo calibre.",
      multa: 3000,
      tempoPrisao: 25,
    },
    {
      id: 2,
      artigo: "13",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Arma Classe 2",
      descricao: "Porte ou posse ilegal de armamento de médio calibre.",
      multa: 5000,
      tempoPrisao: 29,
    },
    {
      id: 3,
      artigo: "14",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Arma Classe 3",
      descricao: "Porte ou posse ilegal de armamento de alto calibre.",
      multa: 9000,
      tempoPrisao: 31,
    },
    {
      id: 4,
      artigo: "16",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Munição",
      descricao: "Portar munições de qualquer calibre até 30 unidades.",
      multa: 6000,
      tempoPrisao: 20,
    },
    {
      id: 5,
      artigo: "17",
      categoria: "pena",
      nome: "Tráfico de Munições",
      descricao: "Portar munições, dolo presumido. A partir de 31 unidades.",
      multa: 8800,
      tempoPrisao: 25,
    },
    {
      id: 6,
      artigo: "18",
      categoria: "pena",
      nome: "Tráfico de Armamento",
      descricao: "Portar dois ou mais armamentos, independente do calibre.",
      multa: 15000,
      tempoPrisao: 30,
    },
    {
      id: 7,
      artigo: "19",
      categoria: "pena",
      nome: "Porte ou Posse Ilegal de Dispositivo Explosivo.",
      descricao: "Portar qualquer dispositivo explosivo.",
      multa: 35000,
      tempoPrisao: 45,
    },
    {
      id: 8,
      artigo: "20",
      categoria: "pena",
      nome: "Tráfico de Dispositivo Explosivo.",
      descricao:
        "Portar dispositivo explosivo, dolo presumido. (Se for de substâncias explosivas ou acessórios que, isoladamente ou em conjunto, permitam sua fabricação, montagem ou uso.)",
      multa: 60500,
      tempoPrisao: 60,
    },
    {
      id: 9,
      artigo: "32",
      categoria: "pena",
      nome: "Porte ou Posse de Drogas",
      descricao: " Portar drogas. Até 10 unidades",
      multa: 1000,
      tempoPrisao: 10,
    },
    {
      id: 10,
      artigo: "33",
      categoria: "pena",
      nome: "Tráfico de Drogas",
      descricao:
        "Posse ou porte de entorpecentes, dolo presumido. A partir de 10 unidades.",
      multa: 2500,
      tempoPrisao: 15,
    },
    {
      id: 11,
      artigo: "121",
      categoria: "pena",
      nome: "Homicídio",
      descricao: "Matar alguém.",
      multa: 30000,
      tempoPrisao: 80,
    },
    {
      id: 12,
      artigo: "121-A",
      categoria: "pena",
      nome: "Homicídio Qualificado",
      descricao:
        " Matar alguém com as seguintes qualificadoras: mediante paga ou promessa de recompensa, ou por outro motivo torpe; por motivo fútil; com fogo, explosivo, tortura ou outro meio insidioso ou cruel, ou de que possa resultar perigo comum; à traição, de emboscada, ou mediante dissimulação ou outro recurso que dificulte ou torne impossível a defesa do ofendido;",
      multa: 50000,
      tempoPrisao: 160,
    },
    {
      id: 13,
      artigo: "121-B",
      categoria: "pena",
      nome: "Homicídio Culposo",
      descricao: "Matar alguém por imprudência, negligência ou imperícia.",
      multa: 25000,
      tempoPrisao: 45,
    },
    {
      id: 14,
      artigo: "121-C",
      categoria: "pena",
      nome: "Homicídio Tentado",
      descricao:
        "Tentativa de homicídio não consumado por circunstâncias alheias à vontade.",
      multa: 19500,
      tempoPrisao: 30,
    },
    {
      id: 15,
      artigo: "121-D",
      categoria: "pena",
      nome: "Feminicídio",
      descricao: "Matar mulher por razões de condição de sexo feminino.",
      multa: 45500,
      tempoPrisao: 100,
    },
    {
      id: 16,
      artigo: "121-E",
      categoria: "pena",
      nome: "Homicídio de Agente Público",
      descricao:
        "Matar agente ou funcionário público, no exercício da função ou em razão dela.",
      multa: 75000,
      tempoPrisao: 175,
    },
    {
      id: 17,
      artigo: "129",
      categoria: "pena",
      nome: "Lesão Corporal",
      descricao: "Ofender a integridade física ou saúde de outrem.",
      multa: 9500,
      tempoPrisao: 17,
    },
    {
      id: 18,
      artigo: "135",
      categoria: "pena",
      nome: "Omissão de Socorro",
      descricao:
        "Causador do dano ou lesão abandona o local sem prestar socorro.",
      multa: 10000,
      tempoPrisao: 25,
    },
    {
      id: 19,
      artigo: "135-A",
      categoria: "pena",
      nome: "Omissão de Socorro de Agente Responsável",
      descricao: "Agente público que, podendo agir, não socorre vítima.",
      multa: 16000,
      tempoPrisao: 28,
    },
    {
      id: 20,
      artigo: "147",
      categoria: "pena",
      nome: "Ameaça",
      descricao: "Ameaçar alguém de causar mal injusto e grave.",
      multa: 5500,
      tempoPrisao: 15,
    },
    {
      id: 21,
      artigo: "148",
      categoria: "pena",
      nome: "Sequestro e Cárcere Privado",
      descricao: "Privar alguém de sua liberdade.",
      multa: 27000,
      tempoPrisao: 45,
    },
    {
      id: 22,
      artigo: "150",
      categoria: "pena",
      nome: "Violação de Domicílio",
      descricao:
        "Entrar ou permanecer em domicílio alheio contra a vontade do morador.",
      multa: 5800,
      tempoPrisao: 15,
    },
    {
      id: 23,
      artigo: "138",
      categoria: "pena",
      nome: "Calúnia",
      descricao: "Imputar falsamente fato definido como crime a alguém.",
      multa: 6000,
      tempoPrisao: 13,
    },
    {
      id: 24,
      artigo: "139",
      categoria: "pena",
      nome: "Difamação",
      descricao: "Imputar fato ofensivo à reputação de alguém.",
      multa: 3000,
      tempoPrisao: 10,
    },
    {
      id: 25,
      artigo: "140",
      categoria: "pena",
      nome: "Injúria",
      descricao: "Ofender a dignidade ou decoro de alguém.",
      multa: 9000,
      tempoPrisao: 18,
    },
    {
      id: 26,
      artigo: "299",
      categoria: "pena",
      nome: "Falsidade Ideológica",
      descricao: "Atribuir identidade falsa para obter vantagem ou prejudicar.",
      multa: 2750,
      tempoPrisao: 10,
    },
    {
      id: 27,
      artigo: "342",
      categoria: "pena",
      nome: "Falso Testemunho",
      descricao: "Faltar com a verdade como testemunha.",
      multa: 3800,
      tempoPrisao: 10,
    },
    {
      id: 28,
      artigo: "155",
      categoria: "pena",
      nome: "Furto",
      descricao: "Subtrair, para si ou outrem, coisa alheia móvel.",
      multa: 9500,
      tempoPrisao: 20,
    },
    {
      id: 29,
      artigo: "155-A",
      categoria: "pena",
      nome: "Furto Qualificado",
      descricao:
        "Subtrair, para si ou para outrem, coisa alheia móvel, quando presente qualquer das circunstâncias agravantes previstas nos parágrafos seguintes: com destruição ou rompimento de obstáculo à subtração da coisa; com abuso de confiança, ou mediante fraude, escalada ou destreza.",
      multa: 9500,
      tempoPrisao: 20,
    },
    {
      id: 30,
      artigo: "157",
      categoria: "pena",
      nome: "Roubo",
      descricao: "Subtrair coisa alheia com violência ou grave ameaça.",
      multa: 16000,
      tempoPrisao: 30,
    },
    {
      id: 31,
      artigo: "157-A",
      categoria: "pena",
      nome: "Roubo Qualificado",
      descricao:
        "Comete o crime descrito no artigo anterior com agravantes previstas nos parágrafos segguintes: Se o crime é cometido com emprego de arma de fogo ou arma branca; Se do crime resulta lesão corporal grave; Se do crime resulta morte; Se há concurso de duas ou mais pessoas.",
      multa: 46000,
      tempoPrisao: 110,
    },
    {
      id: 32,
      artigo: "157-B",
      categoria: "pena",
      nome: "Subtração de Viatura",
      descricao: "Subtrair viatura ou carro oficial.",
      multa: 40500,
      tempoPrisao: 100,
    },
    {
      id: 33,
      artigo: "168",
      categoria: "pena",
      nome: "Apropriação Indébita",
      descricao: "Apropriar-se de bem móvel de que tem posse ou detenção.",
      multa: 9000,
      tempoPrisao: 15,
    },
    {
      id: 34,
      artigo: "171",
      categoria: "pena",
      nome: "Estelionato",
      descricao:
        "Obter vantagem ilícita em prejuízo alheio por meio fraudulento.",
      multa: 19500,
      tempoPrisao: 30,
    },
    {
      id: 35,
      artigo: "180",
      categoria: "pena",
      nome: "Receptação",
      descricao: "Adquirir ou ocultar bem oriundo de crime.",
      multa: 20500,
      tempoPrisao: 35,
    },
    {
      id: 36,
      artigo: "289",
      categoria: "pena",
      nome: "Dinheiro Ilícito",
      descricao: "Portar dinheiro marcado.",
      multa: 25000,
      tempoPrisao: 35,
    },
    {
      id: 37,
      artigo: "330",
      categoria: "pena",
      nome: "Desobediência",
      descricao:
        "Desobedecer ordem legal de funcionário público. (Se do resultado da desobediência ocorre conduta mais gravosa, pode ser aumentada a pena em até 2/3.)",
      multa: 2700,
      tempoPrisao: 10,
    },
    {
      id: 38,
      artigo: "331",
      categoria: "pena",
      nome: "Desacato",
      descricao: "Desacatar funcionário público no exercício da função.",
      multa: 1500,
      tempoPrisao: 12,
    },
    {
      id: 39,
      artigo: "333",
      categoria: "pena",
      nome: "Corrupção",
      descricao: "Obter vantagem indevida em razão da função pública.",
      multa: 7000,
      tempoPrisao: 20,
    },
    {
      id: 40,
      artigo: "333-A",
      categoria: "pena",
      nome: "Suborno",
      descricao: "Oferecer vantagem indevida a funcionário público.",
      multa: 4600,
      tempoPrisao: 17,
    },
    {
      id: 41,
      artigo: "339",
      categoria: "pena",
      nome: "Denunciação Caluniosa",
      descricao: "Acusar falsamente alguém perante a autoridade.",
      multa: 8500,
      tempoPrisao: 17,
    },
    {
      id: 42,
      artigo: "355",
      categoria: "pena",
      nome: "Abuso de Autoridade",
      descricao: "Agir com abuso de poder no exercício da função pública.",
      multa: 12800,
      tempoPrisao: 23,
    },
    {
      id: 43,
      artigo: "357",
      categoria: "pena",
      nome: "Obstrução de Justiça",
      descricao: "Atuar para dificultar investigação ou julgamento.",
      multa: 2600,
      tempoPrisao: 20,
    },
    {
      id: 44,
      artigo: "200",
      categoria: "pena",
      nome: "Disfarce Identitário",
      descricao:
        "Utilizar acessórios, com o intuito de dificultar reconhecimento por parte da autoridade. (Máscaras, capacetes, balaclavas ou similares; Qualquer recurso visual utilizado para disfarçar a fisionomia.)",
      multa: 5000,
      tempoPrisao: 10,
    },
    {
      id: 45,
      artigo: "200-A",
      categoria: "pena",
      nome: "Falsidade Ideológica para agente ou servidor público.",
      descricao:
        "Atribuir a si ou a outrem identidade falsa, adulterar informações ou dados cadastrais, ou induzir autoridade ao erro mediante documentação ou declaração fraudulenta.",
      multa: 7500,
      tempoPrisao: 17,
    },
    {
      id: 46,
      artigo: "201",
      categoria: "pena",
      nome: "Produtos Ilícitos",
      descricao:
        "Portar ou possuir objetos ilícitos conforme decreto judicial.",
      multa: 17000,
      tempoPrisao: 40,
    },
    {
      id: 47,
      artigo: "286",
      categoria: "pena",
      nome: "Apologia ao Crime",
      descricao: "Incitar ou fazer apologia pública ao crime.",
      multa: 750,
      tempoPrisao: 8,
    },
    {
      id: 48,
      artigo: "288",
      categoria: "pena",
      nome: "Associação Criminosa",
      descricao: "Associar-se em 3 ou mais para cometer crimes.",
      multa: 200000,
      tempoPrisao: 220,
    },
    {
      id: 49,
      artigo: "288-A",
      categoria: "pena",
      nome: "Financiamento ao Crime Organizado.",
      descricao:
        "Financiar, patrocinar ou colaborar economicamente ou com qualquer tipo de prestação de serviços para grupos criminosos organizados.",
      multa: 100000,
      tempoPrisao: 190,
    },
    {
      id: 50,
      artigo: "351",
      categoria: "pena",
      nome: "Fuga de Pessoa Custodiada.",
      descricao: "Fugir do local de custódia oficial.",
      multa: 59500,
      tempoPrisao: 43,
    },
    {
      id: 51,
      artigo: "352",
      categoria: "pena",
      nome: "Evasão da Justiça e Obstrução Processual.",
      descricao:
        "Fugir da Justiça por qualquer meio, incluindo ausência injustificada em audiência, evasão ao cumprimento de sentença ou qualquer ordem judicial. A tentativa deliberada de atrapalhar, atrasar ou depredar o andamento regular do processo ou de procedimento legal instaurado.",
      multa: 15000,
      tempoPrisao: 30,
    },
    {
      id: 52,
      artigo: "101",
      categoria: "multa",
      nome: "Dirigir sem habilitação ou CNH vencida",
      descricao: "Conduzir veículo automotor sem possuir Carteira Nacional de Habilitação válida ou com o documento vencido há mais de 30 dias.",
      multa: 7000,
      tempoPrisao: 0,
    },
    {
      id: 53,
      artigo: "102",
      categoria: "multa",
      nome: "Direção Perigosa",
      descricao: "Conduzir veículo em alta velocidade, realizar manobras arriscadas ou colocar em risco a integridade de terceiros.",
      multa: 9000,
      tempoPrisao: 0,
    },
    {
      id: 54,
      artigo: "104",
      categoria: "multa",
      nome: "Estacionamento Indevido",
      descricao: "Estacionar em locais proibidos, calçadas, frente de garagens, vagas especiais sem autorização ou em locais que impeçam a livre circulação.",
      multa: 3000,
      tempoPrisao: 0,
    },
    {
      id: 55,
      artigo: "105",
      categoria: "multa",
      nome: "Ausência de Placa ou Identificação",
      descricao: "Conduzir veículo automotor sem placa visível, com placa adulterada ou sem numeração oficial.",
      multa: 2800,
      tempoPrisao: 0,
    },
    {
      id: 56,
      artigo: "106",
      categoria: "multa",
      nome: "Uso Indevido de Veículo Oficial",
      descricao: "Utilizar viatura ou veículo oficial sem autorização ou para fins pessoais.",
      multa: 15000,
      tempoPrisao: 0,
    },
    {
      id: 57,
      artigo: "107",
      categoria: "multa",
      nome: "Participação em Rachas ou Corridas",
      descricao: "Promover, participar ou incitar rachas, disputas de velocidade ou corridas não autorizadas em via pública.",
      multa: 10500,
      tempoPrisao: 0,
    },
    {
      id: 58,
      artigo: "108",
      categoria: "multa",
      nome: "Conduzir Sob Efeito de Entorpecentes",
      descricao: "Dirigir veículo sob o efeito de substâncias psicoativas ou entorpecentes.",
      multa: 17000,
      tempoPrisao: 0,
    },
    {
      id: 59,
      artigo: "109",
      categoria: "multa",
      nome: "Recusa de Abordagem Policial",
      descricao: "Fugir, desacatar ou desobedecer ordem legal de parada emitida por autoridade policial ou agente de trânsito.",
      multa: 7800,
      tempoPrisao: 0,
    },
    {
      id: 60,
      artigo: "110",
      categoria: "multa",
      nome: "Danos ao Patrimônio Público com Veículo",
      descricao: "Deteriorar, quebrar, colidir ou causar danos a estruturas, equipamentos ou veículos públicos com o uso de automóvel.",
      multa: 18000,
      tempoPrisao: 0,
    },
    {
      id: 61,
      artigo: "111",
      categoria: "multa",
      nome: "Tráfego em Calçadas ou Ciclovias",
      descricao: "Conduzir veículo sobre calçadas, ciclovias ou áreas de pedestres, salvo em casos autorizados ou emergenciais.",
      multa: 6000,
      tempoPrisao: 0,
    },
    {
      id: 62,
      artigo: "112",
      categoria: "multa",
      nome: "Faróis Apagados à Noite ou em Túnel",
      descricao: "Circular à noite ou em túneis sem os faróis devidamente acesos.",
      multa: 1000,
      tempoPrisao: 0,
    },
    {
      id: 63,
      artigo: "113",
      categoria: "multa",
      nome: "Condições Mínimas de Circulação",
      descricao: "Conduzir veículo com ausência de componentes mínimos para locomoção segura, como rodas, volante, bancos ou sistema de direção funcional.",
      multa: 12200,
      tempoPrisao: 0,
    },
    {
      id: 64,
      artigo: "114",
      categoria: "multa",
      nome: "Excesso de Fumaça, Ruído ou Poluição",
      descricao: "Conduzir veículo que emita, de forma excessiva, fumaça, barulho ou outros elementos poluentes.",
      multa: 1800,
      tempoPrisao: 0,
    },
    {
      id: 65,
      artigo: "115",
      categoria: "multa",
      nome: "Uso de Som Excessivo em Veículos",
      descricao: "Emitir som ou música em volume excessivo, perturbando o sossego público ou o funcionamento de órgãos públicos.",
      multa: 2000,
      tempoPrisao: 0,
    },
    {
      id: 66,
      artigo: "116",
      categoria: "multa",
      nome: "Modificações Visuais ou Estruturais Irregulares",
      descricao: "Circular com veículo que possua modificações não autorizadas, que comprometam a identificação ou segurança.",
      multa: 3000,
      tempoPrisao: 0,
    },
    {
      id: 67,
      artigo: "117",
      categoria: "multa",
      nome: "Buzina ou Sirene em Local Inadequado",
      descricao: "Uso de buzina, alarme ou sirene fora de situação de risco ou emergência.",
      multa: 5000,
      tempoPrisao: 0,
    },
    {
      id: 68,
      artigo: "118",
      categoria: "multa",
      nome: "Falta de Equipamentos Obrigatórios",
      descricao: "Circular sem um ou mais dos equipamentos obrigatórios em bom estado: faróis, espelhos, freios, setas, buzina, limpadores ou cinto.",
      multa: 7500,
      tempoPrisao: 0,
    },
    {
      id: 69,
      artigo: "119",
      categoria: "multa",
      nome: "Veículo com Peças Faltantes",
      descricao: "Conduzir veículo automotor com ausência de peças essenciais à sua integridade estrutural ou à segurança da condução, tais como: portas, capô, para-brisa, para-lamas, retrovisores ou bancos.",
      multa: 6000,
      tempoPrisao: 0,
    },
    {
      id: 70,
      artigo: "120",
      categoria: "multa",
      nome: "Pneus em Estado Crítico",
      descricao: "Conduzir veículo com pneus severamente desgastados, com sulcos irregulares, lisos (carecas), ou com estrutura metálica exposta.",
      multa: 6500,
      tempoPrisao: 0,
    },
    {
      id: 71,
      artigo: "121",
      categoria: "multa",
      nome: "Ausência de Equipamentos de Segurança Obrigatórios",
      descricao: "Conduzir veículo com um ou mais dos seguintes itens ausentes ou inoperantes: freios, faróis, lanternas, espelhos retrovisores, setas, buzina, limpador de para-brisa, cinto de segurança ou sistema de direção.",
      multa: 9800,
      tempoPrisao: 0,
    },
    {
      id: 72,
      artigo: "122",
      categoria: "multa",
      nome: "Modificações Mecânicas Perigosas",
      descricao: "Modificar partes mecânicas do veículo de forma a comprometer sua estabilidade ou segurança, tais como: rebaixamento extremo da suspensão; retirada ou modificação de escapamento com corte direto; uso de rodas fora do padrão estrutural original; modificação do sistema de direção ou de frenagem.",
      multa: 9800,
      tempoPrisao: 0,
    },
    {
      id: 73,
      artigo: "123",
      categoria: "multa",
      nome: "Estrutura Comprometida por Colisão",
      descricao: "Conduzir veículo com a estrutura comprometida por acidente anterior, com indícios visíveis de desalinhamento, empenamento, risco de ruptura ou soldagem irregular.",
      multa: 19200,
      tempoPrisao: 0,
    },
  ],
}; 